var t = require('tcomb');
module.exports = {
  errs: t.errs,
  Any: t.Any,
  Nil: t.Nil,
  Bool: t.Bool,
  Num: t.Num,
  Str: t.Str,
  Arr: t.Arr,
  Obj: t.Obj,
  Func: t.Func,
  Err: t.Err,
  Re: t.Re,
  Dat: t.Dat,
  struct: t.struct,
  enums: t.enums,
  union: t.union,
  tuple: t.tuple,
  maybe: t.maybe,
  subtype: t.subtype,
  list: t.list,
  dict: t.dict,
  func: t.func,
  getName: t.util.getName,
  getKind: t.util.getKind,
  mixin: t.util.mixin,
  format: t.util.format
}
